"use client";
import { useState } from "react";
import { useList } from "../../lib/hooks";
import { date } from "../../lib/format";
import { PageHeader } from "../../components/page-header";
import { DataTable } from "../../components/data-table";
import { Modal } from "../../components/modal";
import { FormField } from "../../components/form-field";
type Audit={id:string;createdAt:string;actor?:{name:string}|null;action:string;entityType:string;entityId?:string;requestId?:string;before?:unknown;after?:unknown;reason?:string;ipAddress?:string};
export default function AuditPage(){const[action,setAction]=useState("");const[entity,setEntity]=useState("");const[from,setFrom]=useState("");const[to,setTo]=useState("");const[detail,setDetail]=useState<Audit|null>(null);const list=useList<Audit>("/audit-logs",{action,entityType:entity,dateFrom:from?`${from}T00:00:00+01:00`:undefined,dateTo:to?`${to}T23:59:59.999+01:00`:undefined});return <><PageHeader title="Journal d'audit" description="Une trace immuable des actions sensibles. Aucun mot de passe ni jeton n'est conservé ici."/><div className="toolbar"><FormField label="Action exacte"><input placeholder="Ex. stock.created" value={action} onChange={e=>setAction(e.target.value)}/></FormField><FormField label="Entité"><select value={entity} onChange={e=>setEntity(e.target.value)}><option value="">Toutes les entités</option>{['User','Role','Product','StockMovement','StockIncident','Customer','QUOTE','INVOICE','DELIVERY_NOTE','Payment','BusinessSettings','FileAsset'].map(type=><option key={type}>{type}</option>)}</select></FormField><FormField label="Du"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></FormField><FormField label="Au"><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></FormField></div><DataTable title="Journal d'audit" data={list.data} error={list.error} loading={list.isPending} page={list.page} onPage={list.setPage} columns={[{header:"Date",cell:({row})=>date(row.original.createdAt,true)},{header:"Auteur",cell:({row})=>row.original.actor?.name??"Système"},{header:"Action",accessorKey:"action"},{header:"Entité",accessorKey:"entityType"},{header:"Motif",cell:({row})=><span className="line-clamp-2 max-w-sm">{row.original.reason??"—"}</span>},{header:"Détail",cell:({row})=><button className="quiet-button" onClick={()=>setDetail(row.original)}>Consulter</button>}]}/>{detail&&<Modal open wide onClose={()=>setDetail(null)} title={detail.action} description={`${date(detail.createdAt,true)} - ${detail.actor?.name??"Système"}`}><dl className="mb-5 grid gap-2 text-xs"><div><dt className="font-bold">Entité</dt><dd className="break-all">{detail.entityType} / {detail.entityId??"—"}</dd></div><div><dt className="font-bold">Requête</dt><dd className="break-all">{detail.requestId}</dd></div>{detail.ipAddress&&<div><dt className="font-bold">Adresse IP</dt><dd>{detail.ipAddress}</dd></div>}{detail.reason&&<div><dt className="font-bold">Motif</dt><dd>{detail.reason}</dd></div>}</dl><div className="grid gap-4 md:grid-cols-2">{([['Avant',detail.before],['Après',detail.after]] as const).map(([label,value])=><section key={label}><h2 className="mb-2 font-bold">{label}</h2><pre className="max-h-80 overflow-auto whitespace-pre-wrap break-words rounded-lg bg-slate-50 p-4 text-xs">{JSON.stringify(value??null,null,2)}</pre></section>)}</div></Modal>}</>}
