packages:
  - apps/*
  - packages/*

catalog:
  '@aws-sdk/client-s3': ^3.950.0
  '@fastify/cookie': ^11.0.0
  '@fastify/cors': 11.3.0
  '@fastify/helmet': ^13.0.2
  '@hookform/resolvers': ^5.3.0
  '@nestjs/common': 12.0.1
  '@nestjs/config': 12.0.0
  '@nestjs/core': 12.0.1
  '@nestjs/jwt': ^12.0.0
  '@nestjs/passport': ^12.0.0
  '@nestjs/platform-fastify': 12.0.1
  '@nestjs/swagger': ^12.0.0
  '@nestjs/testing': 12.0.1
  '@nestjs/throttler': ^7.0.0
  '@prisma/client': 7.10.0
  '@tailwindcss/postcss': ^4.1.0
  '@tanstack/react-query': 5.102.8
  '@tanstack/react-table': 8.21.3
  '@zxing/browser': 0.2.1
  argon2: ^0.44.0
  class-transformer: ^0.5.1
  class-validator: ^0.14.3
  cookie: ^1.0.2
  decimal.js: ^10.6.0
  fastify: 5.12.1
  lucide-react: ^0.560.0
  nanoid: ^5.1.6
  nestjs-pino: ^5.0.0
  next: 16.3.4
  next-intl: 4.14.1
  pino: ^10.1.0
  playwright-core: ^1.59.0
  postcss: ^8.5.0
  prisma: 7.10.0
  react: 19.2.8
  react-dom: 19.2.8
  react-hook-form: 7.84.0
  recharts: ^3.5.0
  rxjs: ^7.8.2
  tailwindcss: ^4.1.0
  zod: ^4.2.0

onlyBuiltDependencies:
  - '@prisma/engines'
  - prisma
  - argon2
  - sharp
  - esbuild
