import { moneyLabel, scaled, formatScaled } from "@as-tino/shared";
import type { DocumentSnapshot } from "../documents/document-types.js";

export function escapeHtml(value: unknown): string {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

export function documentHtml(doc: DocumentSnapshot, options: { logoDataUri?: string; watermark?: string; cancellationReason?: string } = {}): string {
  const e = escapeHtml;
  const money = (value: string) => e(moneyLabel(value, doc.currency));
  const numeric = (value: string) => e(value.replace(".", ","));
  const date = (value: string | null) => value
    ? e(new Intl.DateTimeFormat(doc.locale, { timeZone: doc.timezone, day: "2-digit", month: "2-digit", year: "numeric" }).format(new Date(value)))
    : "-";
  const labels = {
    QUOTE: { title: "DEVIS", subtitle: "Offre commerciale", due: "Valable jusqu'au", party: "Client" },
    INVOICE: { title: "FACTURE", subtitle: "Document commercial", due: "Échéance", party: "Facturé à" },
    DELIVERY_NOTE: { title: "BON DE LIVRAISON", subtitle: "Document logistique", due: "Livraison prévue", party: "Destinataire" }
  }[doc.type];
  const taxes = new Map<string, { base: bigint; tax: bigint }>();
  for (const line of doc.lines) {
    const group = taxes.get(line.taxRate) ?? { base: 0n, tax: 0n };
    group.base += scaled(line.taxableAmount);
    group.tax += scaled(line.taxAmount);
    taxes.set(line.taxRate, group);
  }
  const logo = options.logoDataUri && /^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(options.logoDataUri)
    ? `<img class="logo" src="${options.logoDataUri}" alt="Logo de l'entreprise"/>`
    : `<div class="logo-fallback"><strong>G&K</strong><span>COMMERCE</span></div>`;
  const customerAddress = doc.type === "DELIVERY_NOTE"
    ? doc.customer.deliveryAddress || doc.customer.billingAddress
    : doc.customer.billingAddress;
  const hasDiscount = scaled(doc.discountAmount) !== 0n;

  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>${e(labels.title)} ${e(doc.number)}</title>
<style>
@page{size:A4}*{box-sizing:border-box}html{background:#fff}body{margin:0;color:#152c40;font:9.7pt/1.46 Arial,"Noto Sans",sans-serif;-webkit-print-color-adjust:exact;print-color-adjust:exact}
:root{--ink:#152c40;--navy:#123148;--teal:#0f766e;--teal-soft:#e8f5f2;--line:#dce6ec;--muted:#607589;--surface:#f6f9fb;--danger:#a52a36}
.top-accent{height:6px;background:var(--teal);margin:-14mm -14mm 18px}.header{display:flex;justify-content:space-between;align-items:flex-start;gap:24px;padding-bottom:17px;border-bottom:1px solid var(--line)}
.brand{display:flex;align-items:flex-start;gap:14px;min-width:0;max-width:60%}.logo{width:72px;height:62px;object-fit:contain;object-position:left top}.logo-fallback{width:68px;height:58px;padding:10px;border-radius:10px;background:var(--navy);color:#fff;display:flex;flex-direction:column;justify-content:center;line-height:1}.logo-fallback strong{font-size:20px}.logo-fallback span{margin-top:4px;color:#8ee0d2;font-size:7px;font-weight:700;letter-spacing:1.3px}
.company-name{margin:1px 0 5px;font-size:13.5pt;font-weight:800;letter-spacing:-.2px;color:var(--navy)}.company-lines{color:var(--muted);font-size:8.3pt;line-height:1.5;white-space:pre-line;overflow-wrap:anywhere}.company-lines strong{color:var(--ink)}
.doc-id{text-align:right;min-width:190px}.doc-kicker{color:var(--teal);font-size:7.6pt;font-weight:800;letter-spacing:1.65px;text-transform:uppercase}.doc-title{margin:3px 0 3px;color:var(--navy);font-size:25pt;font-weight:850;letter-spacing:-.8px;line-height:1}.doc-number{font-size:11.4pt;font-weight:800;color:var(--teal);font-variant-numeric:tabular-nums}.doc-state{display:inline-block;margin-top:8px;padding:4px 8px;border:1px solid #c9dfdb;border-radius:999px;background:var(--teal-soft);color:#286d67;font-size:7.4pt;font-weight:700}
.document-meta{display:grid;grid-template-columns:1.35fr 1fr 1fr;gap:0;margin:16px 0 18px;border:1px solid var(--line);border-radius:10px;overflow:hidden;background:#fff}.meta-cell{padding:10px 13px;border-right:1px solid var(--line)}.meta-cell:last-child{border-right:0}.meta-label{display:block;margin-bottom:3px;color:var(--muted);font-size:7.3pt;font-weight:800;letter-spacing:.9px;text-transform:uppercase}.meta-value{display:block;color:var(--ink);font-size:9.5pt;font-weight:750}.meta-value.accent{color:var(--teal)}
.party-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:14px;margin-bottom:19px}.party-card{padding:14px 15px;border:1px solid var(--line);border-radius:10px;background:var(--surface);min-height:105px}.party-card.company-card{background:#fff}.section-label{margin-bottom:6px;color:var(--teal);font-size:7.3pt;font-weight:850;letter-spacing:1.15px;text-transform:uppercase}.party-name{margin:0 0 4px;color:var(--navy);font-size:11pt;font-weight:800}.party-line{color:var(--muted);font-size:8.4pt;white-space:pre-line;overflow-wrap:anywhere}.party-line strong{color:var(--ink)}
.alert{margin:0 0 16px;padding:11px 14px;border:1px solid #e2aeb3;border-left:4px solid var(--danger);border-radius:8px;background:#fff7f7;color:#842331;font-size:8.7pt;white-space:pre-line;overflow-wrap:anywhere}.watermark{position:fixed;top:42%;left:0;width:100%;z-index:-1;transform:rotate(-27deg);color:rgba(83,106,122,.12);font-size:48px;font-weight:900;letter-spacing:4px;text-align:center}
.items{width:100%;border-collapse:separate;border-spacing:0;table-layout:fixed;font-size:8.15pt}.items col:nth-child(1){width:5%}.items col:nth-child(2){width:31%}.items col:nth-child(3){width:10%}.items col:nth-child(4){width:12%}.items col:nth-child(5){width:14%}.items col:nth-child(6){width:9%}.items col:nth-child(7){width:7%}.items col:nth-child(8){width:12%}.items thead{display:table-header-group}.items th{padding:9px 6px;background:var(--navy);color:#fff;font-size:7.1pt;font-weight:750;letter-spacing:.25px;text-align:right;vertical-align:middle}.items th:first-child{border-radius:8px 0 0 0}.items th:last-child{border-radius:0 8px 0 0}.items th.desc{text-align:left}.items td{padding:10px 6px;border-bottom:1px solid var(--line);vertical-align:middle;text-align:right;overflow-wrap:anywhere}.items td.desc{text-align:left;white-space:pre-line}.items td.position{text-align:center;color:#8798a7}.items tbody tr:nth-child(even){background:#f8fafb}.items tbody tr{break-inside:avoid}.num{font-variant-numeric:tabular-nums}.strong{font-weight:800;color:var(--navy)}
.summary-grid{display:grid;grid-template-columns:1fr 280px;gap:20px;align-items:start;margin-top:17px;break-inside:avoid}.tax-box{border:1px solid var(--line);border-radius:9px;overflow:hidden}.tax-title{padding:8px 10px;background:var(--surface);color:var(--muted);font-size:7.4pt;font-weight:800;letter-spacing:.8px;text-transform:uppercase}.tax-table{width:100%;border-collapse:collapse;font-size:7.8pt}.tax-table th,.tax-table td{padding:6px 8px;border-top:1px solid var(--line);text-align:right}.tax-table th:first-child,.tax-table td:first-child{text-align:left}.tax-table th{color:var(--muted);font-weight:700}.totals{padding:13px 15px;border:1px solid var(--line);border-radius:10px;background:#fff}.total-row{display:flex;justify-content:space-between;gap:16px;padding:4px 0;color:var(--muted);font-size:8.6pt}.total-row strong{color:var(--ink);white-space:nowrap;font-variant-numeric:tabular-nums}.total-row.discount strong{color:#9a3440}.grand-total{display:flex;justify-content:space-between;align-items:center;gap:16px;margin:9px -15px -13px;padding:12px 15px;border-radius:0 0 9px 9px;background:var(--teal);color:#fff}.grand-total span{font-size:9pt;font-weight:700}.grand-total strong{font-size:14.5pt;white-space:nowrap;font-variant-numeric:tabular-nums}.payment-summary{margin-top:12px;padding-top:10px;border-top:1px dashed #cbd9e0}.payment-summary .total-row{padding:3px 0}.balance-row strong{color:var(--teal);font-size:10pt}
.secondary-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:18px}.info-box{padding:12px 14px;border:1px solid var(--line);border-radius:9px;background:#fff;break-inside:avoid}.info-box h3{margin:0 0 6px;color:var(--navy);font-size:8.6pt}.info-box p{margin:0;color:var(--muted);font-size:8.1pt;line-height:1.5;white-space:pre-line;overflow-wrap:anywhere}.document-note{margin-top:8px;color:#7b8d9d;font-size:7.4pt}
.signatures{display:grid;grid-template-columns:1fr 1fr;gap:38px;margin-top:28px;break-inside:avoid}.signature{min-height:48px;padding-top:8px;border-top:1px solid #8fa3b2;color:var(--muted);font-size:7.7pt}.signature strong{display:block;margin-bottom:2px;color:var(--ink);font-size:8.2pt}.small-note{margin-top:10px;color:#7a8e9f;font-size:7.2pt;line-height:1.4}
</style></head><body>
<div class="top-accent"></div>
${options.watermark ? `<div class="watermark">${e(options.watermark)}</div>` : ""}
<header class="header"><div class="brand">${logo}<div><div class="company-name">${e(doc.company.legalName ?? doc.company.name)}</div><div class="company-lines">${e(doc.company.address)}${doc.company.taxIdentificationNumber ? `\n<strong>Matricule fiscal :</strong> ${e(doc.company.taxIdentificationNumber)}` : ""}${doc.company.email ? `\n${e(doc.company.email)}` : ""}${doc.company.phone ? ` · ${e(doc.company.phone)}` : ""}</div></div></div><div class="doc-id"><div class="doc-kicker">${e(labels.subtitle)}</div><div class="doc-title">${e(labels.title)}</div><div class="doc-number">${e(doc.number)}</div><div class="doc-state">Émis le ${date(doc.issueDate)}</div></div></header>
${options.cancellationReason ? `<div class="alert"><strong>DOCUMENT ANNULÉ</strong><br>${e(options.cancellationReason)}<br>L'original émis reste conservé dans les archives.</div>` : ""}
<section class="document-meta"><div class="meta-cell"><span class="meta-label">Référence</span><span class="meta-value accent">${e(doc.number)}</span></div><div class="meta-cell"><span class="meta-label">Date d'émission</span><span class="meta-value">${date(doc.issueDate)}</span></div><div class="meta-cell"><span class="meta-label">${e(labels.due)}</span><span class="meta-value">${date(doc.dueDate)}</span></div></section>
<section class="party-grid"><div class="party-card"><div class="section-label">${e(labels.party)}</div><div class="party-name">${e(doc.customer.name)}</div>${doc.customer.contactName ? `<div class="party-line"><strong>Contact :</strong> ${e(doc.customer.contactName)}</div>` : ""}<div class="party-line">${e(customerAddress)}</div>${doc.customer.taxIdentificationNumber ? `<div class="party-line"><strong>Matricule fiscal :</strong> ${e(doc.customer.taxIdentificationNumber)}</div>` : ""}<div class="party-line">${e(doc.customer.email)}${doc.customer.email && doc.customer.phone ? " · " : ""}${e(doc.customer.phone)}</div></div><div class="party-card company-card"><div class="section-label">Informations</div><div class="party-line"><strong>Devise :</strong> ${e(doc.currency)}</div><div class="party-line"><strong>Tarification :</strong> Prix unitaires hors taxes</div><div class="party-line"><strong>Précision :</strong> Montants arrondis à trois décimales</div>${doc.type === "QUOTE" ? `<div class="party-line"><strong>Validité :</strong> Jusqu'au ${date(doc.dueDate)}</div>` : ""}${doc.type === "DELIVERY_NOTE" ? `<div class="party-line"><strong>Réception :</strong> À confirmer par le destinataire</div>` : ""}</div></section>
<table class="items"><colgroup>${"<col>".repeat(8)}</colgroup><thead><tr><th>#</th><th class="desc">Désignation</th><th>Quantité</th><th>Unité</th><th>Prix HT</th><th>Remise</th><th>TVA</th><th>Total TTC</th></tr></thead><tbody>${doc.lines.map((line, index) => `<tr><td class="position">${index + 1}</td><td class="desc"><span class="strong">${e(line.description)}</span></td><td class="num">${numeric(line.quantity)}</td><td>${e(line.unit)}</td><td class="num">${numeric(line.unitPrice)}</td><td class="num">${numeric(line.discountRate)} %</td><td class="num">${numeric(line.taxRate)} %</td><td class="num strong">${numeric(line.total)}</td></tr>`).join("")}</tbody></table>
<section class="summary-grid"><div><div class="tax-box"><div class="tax-title">Récapitulatif TVA</div><table class="tax-table"><thead><tr><th>Taux</th><th>Base HT nette</th><th>Montant TVA</th></tr></thead><tbody>${[...taxes].map(([rate, value]) => `<tr><td>${numeric(rate)} %</td><td class="num">${numeric(formatScaled(value.base))}</td><td class="num">${numeric(formatScaled(value.tax))}</td></tr>`).join("")}</tbody></table></div><div class="document-note">Les montants sont exprimés en ${e(doc.currency)}. Le détail des taxes est calculé ligne par ligne.</div></div><div class="totals"><div class="total-row"><span>Sous-total HT</span><strong>${money(doc.subtotal)}</strong></div>${hasDiscount ? `<div class="total-row discount"><span>Remises totales</span><strong>- ${money(doc.discountAmount)}</strong></div>` : ""}<div class="total-row"><span>Total TVA</span><strong>${money(doc.taxAmount)}</strong></div>${doc.documentDiscountRate !== "0.00" && doc.documentDiscountRate !== "0" ? `<div class="small-note">Remise globale : ${numeric(doc.documentDiscountRate)} %</div>` : ""}<div class="grand-total"><span>Total TTC</span><strong>${money(doc.total)}</strong></div>${doc.type === "INVOICE" ? `<div class="payment-summary"><div class="total-row"><span>Réglé à l'émission</span><strong>${money(doc.paidAmount)}</strong></div><div class="total-row balance-row"><span>Solde à l'émission</span><strong>${money(doc.remainingAmount)}</strong></div></div>` : ""}</div></section>
${doc.notes || doc.terms ? `<section class="secondary-grid">${doc.notes ? `<div class="info-box"><h3>Notes</h3><p>${e(doc.notes)}</p></div>` : `<div></div>`}${doc.terms ? `<div class="info-box"><h3>Conditions</h3><p>${e(doc.terms)}</p></div>` : ""}</section>` : ""}
<section class="signatures"><div class="signature"><strong>${doc.type === "QUOTE" ? "Bon pour accord" : doc.type === "DELIVERY_NOTE" ? "Réception du destinataire" : "Client"}</strong>${doc.type === "QUOTE" ? "Nom, date et signature" : doc.type === "DELIVERY_NOTE" ? "Nom, date, signature et réserves éventuelles" : "Signature si requise"}</div><div class="signature"><strong>${e(doc.company.legalName ?? doc.company.name)}</strong>Cachet et signature de l'entreprise</div></section>
</body></html>`;
}

export function documentFooter(doc: DocumentSnapshot): string {
  const company = escapeHtml(doc.company.legalName ?? doc.company.name);
  const number = escapeHtml(doc.number);
  const custom = doc.footer && doc.footer !== "Generated by AS TINO DEV" ? `${escapeHtml(doc.footer)} · ` : "";
  return `<div style="font:7.5px Arial,sans-serif;color:#6e8191;width:100%;margin:0 14mm;display:flex;align-items:center;justify-content:space-between;gap:14px;border-top:1px solid #dce6ec;padding-top:7px"><span><strong style="color:#284257">${company}</strong> · ${number}</span><span>${custom}G&K Stock · Développé par AS TINO DEV</span><span>Page <span class="pageNumber"></span> / <span class="totalPages"></span></span></div>`;
}
