"use client";
import { useState } from "react";
import type { ColumnDef } from "@tanstack/react-table";
import { Button } from "@as-tino/ui";
import type { Payment } from "../../lib/types";
import { useList, useAction } from "../../lib/hooks";
import { date, money, customerName } from "../../lib/format";
import { useFeedback } from "../../providers/feedback-provider";
import { PageHeader } from "../../components/page-header";
import { DataTable } from "../../components/data-table";
import { Modal } from "../../components/modal";
import { FormField, FormError } from "../../components/form-field";
import { PaymentEditor } from "../../components/payment-editor";
import { StatusLabel, statusText } from "../../components/status-label";
export default function PaymentsPage(){const[from,setFrom]=useState("");const[to,setTo]=useState("");const list=useList<Payment>("/payments",{dateFrom:from?`${from}T00:00:00+01:00`:undefined,dateTo:to?`${to}T23:59:59.999+01:00`:undefined});const[create,setCreate]=useState(false);const[cancel,setCancel]=useState<Payment|null>(null);const[reason,setReason]=useState("");const action=useAction();const{confirm}=useFeedback();const columns:ColumnDef<Payment>[]=[{header:"Date",cell:({row})=>date(row.original.paidAt,true)},{header:"Facture",cell:({row})=>row.original.invoice.number??"—"},{header:"Client",cell:({row})=>customerName(row.original.customer)},{header:"Montant",cell:({row})=><strong>{money(row.original.amount)}</strong>},{header:"Mode",cell:({row})=>statusText(row.original.method)},{header:"Référence",cell:({row})=>row.original.reference??"—"},{header:"Statut",cell:({row})=><StatusLabel status={row.original.cancelledAt?"CANCELLED":"REGISTERED"}/>},{header:"Actions",cell:({row})=>!row.original.cancelledAt?<button className="quiet-button danger" onClick={()=>{setCancel(row.original);setReason("");}}>Annuler</button>:<span className="text-xs">{row.original.cancellationReason}</span>}];return <><PageHeader title="Paiements" description="Un suivi exact des règlements, sans suppression de l'historique." action={<Button onClick={()=>setCreate(true)}>Nouveau paiement</Button>}/><div className="toolbar"><select aria-label="Statut du paiement" value={list.status} onChange={e=>list.setStatus(e.target.value)}><option value="">Tous les paiements</option><option value="ACTIVE">Paiements actifs</option><option value="CANCELLED">Paiements annulés</option></select><FormField label="Du"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></FormField><FormField label="Au"><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></FormField></div><DataTable title="Paiements" data={list.data} loading={list.isPending} error={list.error} columns={columns} page={list.page} onPage={list.setPage}/>{create&&<PaymentEditor onClose={()=>setCreate(false)}/>} {cancel&&<Modal open onClose={()=>{if(!action.busy)setCancel(null);}} title="Annuler un paiement" description={`${money(cancel.amount)} - ${cancel.invoice.number}`}><form onSubmit={async e=>{e.preventDefault();if(!await confirm("Annuler ce paiement et rétablir le solde de la facture ?"))return;if(await action.run(`/payments/${cancel.id}/cancel`,{reason}))setCancel(null);}}><FormField label="Motif obligatoire"><textarea required minLength={5} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></FormField><FormError error={action.error}/><div className="form-actions"><Button type="submit" variant="danger" disabled={action.busy}>Confirmer l'annulation</Button></div></form></Modal>}</>}
