"use client";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { useQuery } from "@tanstack/react-query";
import type { ColumnDef } from "@tanstack/react-table";
import { Button } from "@as-tino/ui";
import { Plus } from "lucide-react";
import { apiFetch, queryString } from "../../lib/api";
import { useList, useAction } from "../../lib/hooks";
import { customerName, money, date } from "../../lib/format";
import type { Customer, ApiList } from "../../lib/types";
import { useAuth } from "../../providers/auth-provider";
import { useFeedback } from "../../providers/feedback-provider";
import { PageHeader } from "../../components/page-header";
import { DataTable } from "../../components/data-table";
import { Modal } from "../../components/modal";
import { FormField, FormError } from "../../components/form-field";
import { StatusLabel } from "../../components/status-label";
const schema=z.object({type:z.enum(["COMPANY","INDIVIDUAL"]),companyName:z.string().max(250),contactName:z.string().min(2).max(200),taxIdentificationNumber:z.string().max(250),email:z.union([z.literal(""),z.string().email()]),phone:z.string().max(50),billingAddress:z.string().max(2000),deliveryAddress:z.string().max(2000),notes:z.string().max(4000)}).refine(v=>v.type!=="COMPANY"||!!v.companyName.trim(),{message:"La raison sociale est requise.",path:["companyName"]});
type Values=z.infer<typeof schema>;
export function CustomersClient(){const list=useList<Customer>("/customers");const[editor,setEditor]=useState<Customer|"new"|null>(null);const[timeline,setTimeline]=useState<Customer|null>(null);const action=useAction();const{confirm}=useFeedback();const{can}=useAuth();const columns:ColumnDef<Customer>[]=[{header:"Client",cell:({row})=><div><strong className="block">{customerName(row.original)}</strong><span className="text-xs text-slate-500">{row.original.type==="COMPANY"?"Entreprise":"Particulier"}</span></div>},{header:"Contact",accessorKey:"contactName"},{header:"Coordonnées",cell:({row})=><div><span className="block">{row.original.email||"—"}</span><span className="text-xs text-slate-500">{row.original.phone}</span></div>},{header:"Matricule fiscal",cell:({row})=>row.original.taxIdentificationNumber||"—"},{header:"Actions",cell:({row})=><div className="flex gap-2"><button className="quiet-button" onClick={()=>setEditor(row.original)}>Modifier</button>{can("financial:read")&&<button className="quiet-button" onClick={()=>setTimeline(row.original)}>Historique</button>}{row.original.active&&<button className="quiet-button danger" disabled={action.busy} onClick={async()=>{if(await confirm(`Archiver ${customerName(row.original)} ? Les documents restent conservés.`))await action.run(`/customers/${row.original.id}/archive`,undefined,{method:"PATCH"});}}>Archiver</button>}</div>}];return <><PageHeader title="Clients" description="Toutes les coordonnées utiles et l'historique de vos relations commerciales." action={<Button onClick={()=>setEditor("new")}><Plus size={16}/>Nouveau client</Button>}/><div className="toolbar"><input aria-label="Rechercher un client" placeholder="Nom, entreprise, e-mail..." value={list.search} onChange={e=>list.setSearch(e.target.value)}/><select aria-label="Statut du client" value={list.status} onChange={e=>list.setStatus(e.target.value)}><option value="">Clients actifs</option><option value="ARCHIVED">Clients archivés</option></select></div><DataTable title="Clients" data={list.data} loading={list.isPending} error={list.error} columns={columns} page={list.page} onPage={list.setPage}/>{editor&&<CustomerEditor customer={editor==="new"?undefined:editor} onClose={()=>setEditor(null)}/>} {timeline&&<CustomerTimeline customer={timeline} onClose={()=>setTimeline(null)}/>}</>}
function CustomerEditor({customer,onClose}:{customer?:Customer;onClose:()=>void}){const action=useAction();const{register,handleSubmit,watch,formState:{errors}}=useForm<Values>({resolver:zodResolver(schema),defaultValues:{type:customer?.type??"COMPANY",companyName:customer?.companyName??"",contactName:customer?.contactName??"",taxIdentificationNumber:customer?.taxIdentificationNumber??"",email:customer?.email??"",phone:customer?.phone??"",billingAddress:customer?.addresses?.find(a=>a.kind==="BILLING")?.rawText??"",deliveryAddress:customer?.addresses?.find(a=>a.kind==="DELIVERY")?.rawText??"",notes:customer?.notes??""}});return <Modal open onClose={()=>{if(!action.busy)onClose();}} title={customer?"Modifier le client":"Nouveau client"} description="Les documents émis conservent les coordonnées au jour de l'émission."><form onSubmit={handleSubmit(async values=>{const result=await action.run<Customer>(customer?`/customers/${customer.id}`:"/customers",{...values,email:values.email||undefined},{method:customer?"PATCH":"POST"});if(result)onClose();})}><div className="form-grid"><FormField label="Type de client"><select {...register("type")}><option value="COMPANY">Entreprise</option><option value="INDIVIDUAL">Particulier</option></select></FormField><FormField label={watch("type")==="COMPANY"?"Raison sociale *":"Raison sociale"} error={errors.companyName?.message}><input {...register("companyName")}/></FormField>{([['contactName','Nom du contact *'],['taxIdentificationNumber','Matricule fiscal'],['email','E-mail'],['phone','Téléphone']] as const).map(([key,label])=><FormField key={key} label={label} error={errors[key]?.message}><input type={key==="email"?"email":"text"} {...register(key)} aria-invalid={!!errors[key]}/></FormField>)}<FormField label="Adresse de facturation"><textarea rows={3} {...register("billingAddress")}/></FormField><FormField label="Adresse de livraison"><textarea rows={3} {...register("deliveryAddress")}/></FormField><FormField label="Notes internes" className="full"><textarea rows={3} {...register("notes")}/></FormField></div><FormError error={action.error}/><div className="form-actions"><Button variant="secondary" type="button" onClick={onClose} disabled={action.busy}>Annuler</Button><Button disabled={action.busy} type="submit">Enregistrer le client</Button></div></form></Modal>}
type Event={id:string;type:string;number:string;date:string;amount:string;status:string};
function CustomerTimeline({customer,onClose}:{customer:Customer;onClose:()=>void}){const[page,setPage]=useState(1);const query=useQuery({queryKey:["/customers",customer.id,"timeline",page],queryFn:()=>apiFetch<ApiList<Event>>(`/customers/${customer.id}/timeline${queryString({page})}`)});const labels:Record<string,string>={QUOTE:"Devis",INVOICE:"Facture",DELIVERY_NOTE:"Bon de livraison",PAYMENT:"Paiement"};return <Modal open onClose={onClose} title={customerName(customer)} description="Devis, factures, livraisons et règlements." wide><DataTable data={query.data} loading={query.isPending} error={query.error} page={page} onPage={setPage} title="Historique du client" columns={[{header:"Date",cell:({row})=>date(row.original.date)},{header:"Type",cell:({row})=>labels[row.original.type]??row.original.type},{header:"Référence",accessorKey:"number"},{header:"Montant",cell:({row})=>money(row.original.amount)},{header:"Statut",cell:({row})=><StatusLabel status={row.original.status}/>} ]}/></Modal>}
