"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Button } from "@as-tino/ui";
import { apiFetch } from "../../lib/api";
import { AuthLayout } from "../../components/auth-layout";
import { FormField, FormError } from "../../components/form-field";
export default function ResetPassword(){const[token,setToken]=useState("");const[password,setPassword]=useState("");const[repeat,setRepeat]=useState("");const[busy,setBusy]=useState(false);const[done,setDone]=useState(false);const[error,setError]=useState("");useEffect(()=>{setToken(new URLSearchParams(location.hash.slice(1)).get("token")??"");history.replaceState(null,"",location.pathname);},[]);
return <AuthLayout><h1>Nouveau mot de passe</h1><p>Choisissez au moins 12 caractères. Vos autres sessions seront déconnectées.</p>{done?<div role="status"><p>Votre mot de passe a été modifié.</p><Link href="/connexion" className="text-teal-700 underline">Se connecter</Link></div>:<form onSubmit={async e=>{e.preventDefault();if(busy)return;if(password!==repeat){setError("Les mots de passe ne correspondent pas.");return;}setBusy(true);setError("");try{await apiFetch("/auth/password-reset/confirm",{method:"POST",json:{token,password},noRefresh:true});setPassword("");setRepeat("");setToken("");setDone(true);}catch(err){setError(err instanceof Error?err.message:"Lien invalide.");}finally{setBusy(false);}}}><FormField label="Nouveau mot de passe"><input type="password" minLength={12} maxLength={128} required autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></FormField><FormField label="Confirmer le mot de passe"><input type="password" required autoComplete="new-password" value={repeat} onChange={e=>setRepeat(e.target.value)}/></FormField><FormError error={error||(!token?"Ouvrez le lien reçu par e-mail pour continuer.":null)}/><Button disabled={busy||!token} type="submit">Enregistrer le mot de passe</Button></form>}</AuthLayout>}
