"use client";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { useQuery } from "@tanstack/react-query";
import type { ColumnDef } from "@tanstack/react-table";
import { Button, StatusBadge } from "@as-tino/ui";
import { moneyStringSchema, rateSchema, scaled } from "@as-tino/shared";
import { Plus, Package } from "lucide-react";
import { apiFetch } from "../../lib/api";
import { useAction, useList } from "../../lib/hooks";
import { money, quantity } from "../../lib/format";
import type { Product, Category, Warehouse } from "../../lib/types";
import { useAuth } from "../../providers/auth-provider";
import { useFeedback } from "../../providers/feedback-provider";
import { PageHeader } from "../../components/page-header";
import { DataTable } from "../../components/data-table";
import { Modal } from "../../components/modal";
import { FormField, FormError } from "../../components/form-field";
import { ImageUpload } from "../../components/image-upload";
import { BarcodeProductField } from "../../components/barcode-product-field";
const schema=z.object({sku:z.string().trim().min(1).max(80),barcode:z.string().trim().max(150),name:z.string().trim().min(2).max(200),description:z.string().max(4000),categoryId:z.string(),unit:z.string().min(1).max(30),purchasePrice:moneyStringSchema,sellingPrice:moneyStringSchema,taxRate:rateSchema,minimumStock:moneyStringSchema,location:z.string().max(250),imageAssetId:z.string()});
type Values=z.infer<typeof schema>;
export function ProductsClient(){const {can}=useAuth();const {confirm}=useFeedback();const action=useAction();const[categoryId,setCategoryId]=useState("");const list=useList<Product>("/products",{categoryId});const[catalog,setCatalog]=useState(false);const[editor,setEditor]=useState<Product|"new"|null>(null);const categories=useQuery({queryKey:["/categories"],queryFn:()=>apiFetch<Category[]>("/categories")});
const columns:ColumnDef<Product>[]=[{header:"Produit",cell:({row})=><div className="flex items-center gap-3">{row.original.imageUrl?<img src={row.original.imageUrl} alt="" width={40} height={40} className="h-10 w-10 rounded-lg object-cover"/>:<span className="rounded-lg bg-slate-100 p-2 text-slate-400"><Package size={22}/></span>}<div><strong className="block text-slate-800">{row.original.name}</strong><span className="text-xs text-slate-500">{row.original.sku}{row.original.barcode?` · ${row.original.barcode}`:""}</span></div></div>},{header:"Catégorie",cell:({row})=>row.original.category?.name??"—"},{header:"Stock disponible",cell:({row})=><div><strong className={row.original.lowStock?"text-amber-800":"text-slate-800"}>{quantity(row.original.quantity)} {row.original.unit}</strong><div className="mt-1">{scaled(row.original.quantity)<=0n?<StatusBadge tone="red">Rupture</StatusBadge>:row.original.lowStock?<StatusBadge tone="amber">Stock faible</StatusBadge>:<span className="text-xs text-slate-400">Minimum : {quantity(row.original.minimumStock)}</span>}</div></div>},{header:"Emplacement",cell:({row})=>row.original.location||"—"},...(can("financial:read")?[{header:"Prix de vente HT",cell:({row}:{row:{original:Product}})=>money(row.original.sellingPrice)}]:[]),{header:"Actions",cell:({row})=>can("product:write")?<div className="flex gap-2"><button className="quiet-button" onClick={()=>setEditor(row.original)}>Modifier</button>{row.original.status==="ACTIVE"&&<button className="quiet-button danger" disabled={action.busy} onClick={async()=>{if(await confirm(`Archiver ${row.original.name} ? Son historique restera conservé.`))await action.run(`/products/${row.original.id}/archive`,undefined,{method:"PATCH"});}}>Archiver</button>}</div>:<span className="text-xs text-slate-400">Lecture seule</span>}];
return <><PageHeader title="Produits" description="Un catalogue organisé, des disponibilités en temps réel." action={can("product:write")&&<div className="flex gap-2"><Button variant="secondary" onClick={()=>setCatalog(true)}>Catégories et dépôts</Button><Button onClick={()=>setEditor("new")}><Plus size={16}/>Nouveau produit</Button></div>}/><div className="toolbar"><input aria-label="Rechercher un produit" placeholder="Nom, SKU ou code-barres..." value={list.search} onChange={e=>list.setSearch(e.target.value)}/><select aria-label="Catégorie" value={categoryId} onChange={e=>setCategoryId(e.target.value)}><option value="">Toutes les catégories</option>{categories.data?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{can("product:write")&&<select aria-label="Statut du produit" value={list.status} onChange={e=>list.setStatus(e.target.value)}><option value="">Produits actifs</option><option value="ARCHIVED">Produits archivés</option></select>}</div><DataTable data={list.data} loading={list.isPending} error={list.error} columns={columns} page={list.page} onPage={list.setPage} title="Produits" retry={()=>void list.refetch()}/>{editor&&<ProductEditor product={editor==="new"?undefined:editor} categories={categories.data??[]} onClose={()=>setEditor(null)}/>}<CatalogModal open={catalog} onClose={()=>setCatalog(false)}/></>;}
function ProductEditor({product,categories,onClose}:{product?:Product;categories:Category[];onClose:()=>void}){const action=useAction();const {register,handleSubmit,setValue,watch,formState:{errors}}=useForm<Values>({resolver:zodResolver(schema),defaultValues:{sku:product?.sku??"",barcode:product?.barcode??"",name:product?.name??"",description:product?.description??"",categoryId:product?.categoryId??"",unit:product?.unit??"piece",purchasePrice:product?.purchasePrice??"0.000",sellingPrice:product?.sellingPrice??"0.000",taxRate:product?.taxRate??"19",minimumStock:product?.minimumStock??"0",location:product?.location??"",imageAssetId:product?.imageAssetId??""}});
return <Modal open onClose={()=>{if(!action.busy)onClose();}} title={product?"Modifier le produit":"Nouveau produit"} description="Le stock est modifié uniquement par un mouvement traçable, jamais dans cette fiche."><form onSubmit={handleSubmit(async values=>{const body={...values,barcode:values.barcode||undefined,categoryId:values.categoryId||undefined,imageAssetId:values.imageAssetId||undefined};const result=await action.run<Product>(product?`/products/${product.id}`:"/products",body,{method:product?"PATCH":"POST"});if(result)onClose();})}><div className="form-grid"><FormField label="Nom du produit *" error={errors.name?.message} className="full"><input {...register("name")} aria-invalid={!!errors.name}/></FormField><FormField label="SKU *" error={errors.sku?.message}><input {...register("sku")} aria-invalid={!!errors.sku}/></FormField><BarcodeProductField value={watch("barcode")} onChange={value=>setValue("barcode",value,{shouldDirty:true,shouldValidate:true})} currentProductId={product?.id} error={errors.barcode?.message}/><FormField label="Catégorie"><select {...register("categoryId")}><option value="">Sans catégorie</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></FormField><FormField label="Unité *" error={errors.unit?.message}><input {...register("unit")}/></FormField>{([['purchasePrice','Prix d’achat HT (TND)'],['sellingPrice','Prix de vente HT (TND)'],['taxRate','TVA (%)'],['minimumStock','Seuil de stock minimum']] as const).map(([key,label])=><FormField key={key} label={label} error={errors[key]?.message}><input inputMode="decimal" {...register(key)} aria-invalid={!!errors[key]}/></FormField>)}<FormField label="Emplacement" className="full"><input {...register("location")}/></FormField><FormField label="Description" className="full"><textarea rows={3} {...register("description")}/></FormField><div className="full"><ImageUpload onUpload={id=>setValue("imageAssetId",id)}/></div></div><FormError error={action.error}/><div className="form-actions"><Button variant="secondary" type="button" onClick={onClose} disabled={action.busy}>Annuler</Button><Button type="submit" disabled={action.busy}>{action.busy?"Enregistrement...":"Enregistrer le produit"}</Button></div></form></Modal>}
function CatalogModal({open,onClose}:{open:boolean;onClose:()=>void}){const{can}=useAuth();const[cname,setCname]=useState("");const[wname,setWname]=useState("");const[code,setCode]=useState("");const action=useAction();const cats=useQuery({queryKey:["/categories"],queryFn:()=>apiFetch<Category[]>("/categories"),enabled:open});const warehouses=useQuery({queryKey:["/warehouses"],queryFn:()=>apiFetch<Warehouse[]>("/warehouses"),enabled:open});return <Modal open={open} onClose={onClose} title="Catégories et dépôts" description="Les mouvements restent liés à leur dépôt d'origine."><div className="stack"><section><h2 className="mb-3 font-bold">Catégories</h2><p className="mb-3 text-sm text-slate-500">{cats.data?.map(c=>c.name).join(" · ")||"Aucune catégorie."}</p><form className="flex gap-2" onSubmit={async e=>{e.preventDefault();if(await action.run("/categories",{name:cname}))setCname("");}}><input aria-label="Nouvelle catégorie" placeholder="Nom de la catégorie" required minLength={2} maxLength={100} value={cname} onChange={e=>setCname(e.target.value)}/><Button disabled={action.busy} type="submit">Ajouter</Button></form></section><section><h2 className="mb-3 font-bold">Dépôts</h2><p className="mb-3 text-sm text-slate-500">{warehouses.data?.map(w=>`${w.code} - ${w.name}`).join(" · ")}</p>{can("stock:adjust")&&<form className="grid gap-3" onSubmit={async e=>{e.preventDefault();if(await action.run("/warehouses",{code,name:wname})){setWname("");setCode("");}}}><FormField label="Code du dépôt"><input required value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></FormField><FormField label="Nom du dépôt"><input required value={wname} onChange={e=>setWname(e.target.value)}/></FormField><Button disabled={action.busy} type="submit">Ajouter le dépôt</Button></form>}</section><FormError error={action.error}/></div></Modal>}
